server:
  port: 8080
opentracing:
  jaeger:
    http-sender:
      #url: "http://jaeger-all-in-one-inmemory-collector.jaeger:14268/api/traces"
      #url: "http://jaeger-all-in-one-inmemory-collector-headless.jaeger:14268/api/traces"
      #url: "http://jaeger-all-in-one-inmemory-collector-headless.jaegers:14268/api/traces"
      url: "http://jaeger-collector-headless-istio-system.apps-crc.testing/api/traces"
      username: kubeadmin
      password: "cznQP-n4pBk-cnXTg-nkevH"
      #authtoken: token
    log-spans: true
    service-name: openshift-demo
    enable-b3-propagation: true