apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "wcm-bpm"
spec:
  host: "*.wcm-bpm.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL